### ISSUE TITLE
安装 pip 时报错

### ISSUE THREAD

**Issue by tlin2011** [CatchZeng/Localizable.strings2Excel#28]
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

python 版本是2.7，  执行  sudo python get-pip.py 时一直报错，无法安装pip， 我怀疑 下载的get-pip.py 是 python3 的语法。

Traceback (most recent call last):
  File "get-pip.py", line 24226, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "/tmp/tmpX9NOZq/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")

SyntaxError: invalid syntax

**Comment by CatchZeng** [comment]
这个问题是安装 pip 的问题，不是本项目的问题，建议查找下安装 pip 的教程，或者 google 下报错的原因。
