### ISSUE TITLE
文件未找到

### ISSUE THREAD

**Issue by harryzjm** [CatchZeng/Localizable.strings2Excel#7]
```  
Traceback (most recent call last):
  File "Localizable.py", line 71, in <module>
    main()
  File "Localizable.py", line 69, in main
    startConvert(options)
  File "Localizable.py", line 46, in startConvert
    (keys, values) = LocalizableStringsFileUtil.getKeysAndValues(path)
  File "/Users/Hares/Documents/Res/Store/Third/Localizable.strings2Excel/python/LocalizableStringsFileUtil.py", line 43, in getKeysAndValues
    file = codecs.open(path, 'r', 'utf-8')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 884, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '../ios/zh-Hans.lproj/Localizable.strings'
```  

若是直接在你的文件打开修改 没有问题 而我直接把项目语言文件夹拉进去 覆盖后  
run起来就报这错  我检查过 权限和 所有人 都是一样的 不知道什么原因 难道是编码?

**Comment by harryzjm** [comment]
我去 我的错 命名多了一个q
